apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi # Dung lượng lưu trữ
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain # Quy tắc khi pod hủy liên kết PV
  hostPath:
     path: "/mnt/d/BigData/HUST_IT4931/spark/code"
