apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datanode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: datanode
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              valueFrom:
                configMapKeyRef:
                  key: CORE_CONF_fs_defaultFS
                  name: hadoop-env
            - name: HDFS_CONF_dfs_replication
              valueFrom:
                configMapKeyRef:
                  key: HDFS_CONF_dfs_replication
                  name: hadoop-env
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          name: datanode
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: hadoop-datanode
      restartPolicy: Always
      volumes:
        - name: hadoop-datanode
          persistentVolumeClaim:
            claimName: hadoop-datanode
