apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datanode
  name: datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              valueFrom:
                configMapKeyRef:
                  key: CORE_CONF_fs_defaultFS
                  name: hadoop-env
            - name: HDFS_CONF_dfs_replication
              valueFrom:
                configMapKeyRef:
                  key: HDFS_CONF_dfs_replication
                  name: hadoop-env
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          name: datanode
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: hadoop-datanode
      restartPolicy: Always
      volumes:
        - name: hadoop-datanode
          persistentVolumeClaim:
            claimName: hadoop-datanode
