apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  labels:
    app: hadoop
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode:8020
  HDFS_CONF_dfs_replication: "1"
  HDFS_CONF_dfs_webhdfs_enabled: "true"  # Bật WebHDFS
  HDFS_CONF_dfs_namenode_http_address: "0.0.0.0:9870"  # Gắn cổng HTTP
