apiVersion: v1
data:
  CORE_CONF_fs_defaultFS: hdfs://namenode:8020
  HDFS_CONF_dfs_replication: "1"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: datanode-hadoop-env
  name: hadoop-env
