apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: "9093"
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka
  type: ClusterIP

