apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    app: namenode
