apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: namenode
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: bigdata_cluster
            - name: CORE_CONF_fs_defaultFS
              valueFrom:
                configMapKeyRef:
                  key: CORE_CONF_fs_defaultFS
                  name: hadoop-env
            - name: HDFS_CONF_dfs_replication
              valueFrom:
                configMapKeyRef:
                  key: HDFS_CONF_dfs_replication
                  name: hadoop-env
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          name: namenode
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 8020
              protocol: TCP
          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: hadoop-namenode
            - mountPath: /datasets
              name: namenode-claim1
      restartPolicy: Always
      volumes:
        - name: hadoop-namenode
          persistentVolumeClaim:
            claimName: hadoop-namenode
        - name: namenode-claim1
          persistentVolumeClaim:
            claimName: namenode-claim1
