apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: spark-code
  name: spark-code
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi