apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: spark-code
  name: spark-code
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
